# Generated by Django 5.0.14 on 2025-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplychain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loom",
            name="loom_type",
            field=models.CharField(
                choices=[
                    ("traditional", "Traditional"),
                    ("semi-automatic", "Semi-Automatic"),
                    ("automatic", "Automatic"),
                ],
                default="traditional",
                max_length=20,
            ),
        ),
    ]
