# Generated by Django 5.0.14 on 2025-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplychain", "0002_loom_loom_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("yarn", "Yarn"),
                            ("dye", "Dye"),
                            ("chemical", "Chemical"),
                            ("finished_product", "Finished Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "minimum_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Inventory",
                "ordering": ["material_type", "name"],
            },
        ),
    ]
