# Generated by Django 5.0.14 on 2025-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplychain", "0003_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_production", "In Production"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
